// <auto-generated />
namespace Pharmacy_Management_System1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TotalProductAmount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TotalProductAmount));
        
        string IMigrationMetadata.Id
        {
            get { return "202306041537577_TotalProductAmount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
